"""migrate_drop_row.py — One-time migration: remove ROW from all persisted data.

Context (see PROJECT_STATE.md §1.2 finding #12, §2 decision 1):
Leontief/technical-coefficient matrices and edge tables were built with ROW
("Rest of World") included as the 44th country (2464 = 44*56 nodes), but
node_features_*.parquet never had ROW (WIOD socioeconomic accounts have no
ROW row) — 2408 = 43*56 rows only. Decision: drop ROW entirely. This script
migrates all already-persisted 2000-2014 files that still carry ROW to the
new 43-country / 2408-node universe defined in config.py.

Does NOT touch edges_2015..2021.parquet (Comtrade-extension years) — those
are regenerated by rerunning src/data/extend_with_comtrade.py from the fixed
edges_2014.parquet structural prior, and technical_coefficients/leontief
files are regenerated by rerunning build_technical_coefficients.py and
compute_leontief.py from the fixed edges_raw_*.parquet.

Run once:
    python scripts/migrate_drop_row.py
"""

import os
import sys

import pandas as pd

_here = os.path.dirname(__file__)
PROJECT_ROOT = os.path.abspath(os.path.join(_here, ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import config  # noqa: E402

COUNTRY_LIST = config.GRAPH["COUNTRY_LIST"]   # 43 entries, ROW already removed
SECTOR_LIST = config.GRAPH["SECTOR_LIST"]     # 56 entries
N_SECTORS = config.GRAPH["N_SECTORS"]
N_NODES = config.GRAPH["N_NODES"]

assert "ROW" not in COUNTRY_LIST, "config.py still contains ROW — fix config first"
assert len(COUNTRY_LIST) == 43, f"Expected 43 countries, got {len(COUNTRY_LIST)}"
assert N_NODES == 2408, f"Expected N_NODES=2408, got {N_NODES}"

_COUNTRY_IDX = {c: i for i, c in enumerate(COUNTRY_LIST)}
_SECTOR_IDX = {s: i for i, s in enumerate(SECTOR_LIST)}

EDGES_DIR = os.path.join(PROJECT_ROOT, config.PATHS["PROCESSED_EDGES"])
TARIFF_PATH = os.path.join(PROJECT_ROOT, config.PATHS["PROCESSED_TARIFF_RATES"], "sector_tariffs.parquet")
SHOCK_DIR = os.path.join(PROJECT_ROOT, config.PATHS["PROCESSED_SHOCK_VECTORS"])

WIOD_YEARS = [y for y in config.GRAPH["WIOD_YEARS"] if 2000 <= y <= 2014]


def _node_id(country: str, sector: str) -> int:
    return _COUNTRY_IDX[country] * N_SECTORS + _SECTOR_IDX[sector]


def fix_edge_file(path: str) -> None:
    if not os.path.exists(path):
        print(f"  SKIP (not found): {path}")
        return
    df = pd.read_parquet(path)
    n_before = len(df)
    if "ROW" not in set(df["src_country"].astype(str)) | set(df["tgt_country"].astype(str)):
        print(f"  SKIP (already ROW-free): {path} ({n_before} rows)")
        return

    df["src_country"] = df["src_country"].astype(str)
    df["tgt_country"] = df["tgt_country"].astype(str)
    df["src_sector"] = df["src_sector"].astype(str)
    df["tgt_sector"] = df["tgt_sector"].astype(str)

    df = df[(df["src_country"] != "ROW") & (df["tgt_country"] != "ROW")].copy()

    df["src_id"] = [
        _node_id(c, s) for c, s in zip(df["src_country"], df["src_sector"])
    ]
    df["tgt_id"] = [
        _node_id(c, s) for c, s in zip(df["tgt_country"], df["tgt_sector"])
    ]

    df["year"] = df["year"].astype("int16")
    df["src_country"] = df["src_country"].astype("category")
    df["src_sector"] = df["src_sector"].astype("category")
    df["tgt_country"] = df["tgt_country"].astype("category")
    df["tgt_sector"] = df["tgt_sector"].astype("category")
    df["flow_usd"] = df["flow_usd"].astype("float32")
    df["import_pen_coeff"] = df["import_pen_coeff"].astype("float32")
    df["src_id"] = df["src_id"].astype("int16")
    df["tgt_id"] = df["tgt_id"].astype("int16")

    assert df["src_id"].between(0, N_NODES - 1).all(), f"{path}: src_id out of range"
    assert df["tgt_id"].between(0, N_NODES - 1).all(), f"{path}: tgt_id out of range"

    df.to_parquet(path, engine="pyarrow", index=False)
    print(f"  FIXED: {path}  {n_before} -> {len(df)} rows")


def fix_tariff_rates() -> None:
    if not os.path.exists(TARIFF_PATH):
        print(f"  SKIP (not found): {TARIFF_PATH}")
        return
    df = pd.read_parquet(TARIFF_PATH)
    n_before = len(df)
    df["country"] = df["country"].astype(str)
    row_mask = df["country"] == "ROW"
    n_row = int(row_mask.sum())
    n_row_nonmissing = int((row_mask & (df["data_source"] != "missing")).sum())
    if n_row_nonmissing > 0:
        print(f"  WARNING: {n_row_nonmissing} ROW rows in tariff_rates have real "
              f"(non-missing) data — dropping anyway per decision, but flagging.")
    df = df[~row_mask].copy()
    df["country"] = df["country"].astype("category")
    df["sector"] = df["sector"].astype("category")
    df.to_parquet(TARIFF_PATH, engine="pyarrow", index=False)
    print(f"  FIXED: {TARIFF_PATH}  {n_before} -> {len(df)} rows (dropped {n_row} ROW rows)")


def fix_shock_vectors() -> None:
    if not os.path.isdir(SHOCK_DIR):
        print(f"  SKIP (dir not found): {SHOCK_DIR}")
        return
    for fname in sorted(os.listdir(SHOCK_DIR)):
        if not fname.startswith("shock_") or not fname.endswith(".parquet"):
            continue
        path = os.path.join(SHOCK_DIR, fname)
        df = pd.read_parquet(path)
        n_before = len(df)
        df["src_country"] = df["src_country"].astype(str)
        df["tgt_country"] = df["tgt_country"].astype(str)
        row_mask = (df["src_country"] == "ROW") | (df["tgt_country"] == "ROW")
        n_row = int(row_mask.sum())
        n_row_nonzero = int((row_mask & (df["delta_tariff"] != 0)).sum())
        if n_row == 0:
            print(f"  SKIP (already ROW-free): {path} ({n_before} rows)")
            continue
        df = df[~row_mask].copy()
        df["src_country"] = df["src_country"].astype("category")
        df["tgt_country"] = df["tgt_country"].astype("category")
        df["sector"] = df["sector"].astype("category")
        df.to_parquet(path, engine="pyarrow", index=False)
        print(f"  FIXED: {path}  {n_before} -> {len(df)} rows "
              f"(dropped {n_row} ROW rows, {n_row_nonzero} had nonzero delta_tariff)")


def main() -> None:
    print("=" * 60)
    print("Migrating persisted data to drop ROW (43 countries, 2408 nodes)")
    print("=" * 60)

    print("\n[1/3] edges_raw_{YEAR}.parquet and edges_{YEAR}.parquet (2000-2014):")
    for year in WIOD_YEARS:
        fix_edge_file(os.path.join(EDGES_DIR, f"edges_raw_{year}.parquet"))
        fix_edge_file(os.path.join(EDGES_DIR, f"edges_{year}.parquet"))

    print("\n[2/3] sector_tariffs.parquet:")
    fix_tariff_rates()

    print("\n[3/3] shock_vectors/shock_*.parquet:")
    fix_shock_vectors()

    print("\nDone. Next steps (not run by this script):")
    print("  - delete stale data/processed/technical_coefficients/A_*.npz")
    print("  - delete stale data/processed/leontief/leontief_*.npy and backward_linkage_*.npy")
    print("  - rerun src/data/build_technical_coefficients.py and src/data/compute_leontief.py")
    print("  - delete stale data/processed/edges/edges_{2015..2021}.parquet")
    print("  - rerun src/data/extend_with_comtrade.py")


if __name__ == "__main__":
    main()
